apiVersion: v2
name: rocketpool
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.11.6"

dependencies:
  - name: ethereum-node
    alias: primaryNode
    version: 0.0.23
    condition: primaryNode.enabled
    repository: https://ethpandaops.github.io/ethereum-helm-charts
  - name: ethereum-node
    alias: fallbackNode
    version: 0.0.23
    condition: fallbackNode.enabled
    repository: https://ethpandaops.github.io/ethereum-helm-charts
  - name: grandine
    version: 0.0.1
    condition: global.validator.grandine
    repository: https://ethpandaops.github.io/ethereum-helm-charts
  - name: lighthouse
    version: 1.1.2
    condition: global.validator.lighthouse
    repository: https://ethpandaops.github.io/ethereum-helm-charts
  - name: lodestar
    version: 1.1.2
    condition: global.validator.lodestar
    repository: https://ethpandaops.github.io/ethereum-helm-charts
  - name: nimbus
    version: 1.1.1
    condition: global.validator.nimbus
    repository: https://ethpandaops.github.io/ethereum-helm-charts
  - name: prysm
    version: 1.1.2
    condition: global.validator.prysm
    repository: https://ethpandaops.github.io/ethereum-helm-charts
  - name: teku
    version: 1.1.2
    condition: global.validator.teku
    repository: https://ethpandaops.github.io/ethereum-helm-charts
