global:
  main:
    network: &global-network holesky
  checkpointSync:
    enabled: false

rocketPool:
  bitflyNodeMetrics:
    bitflyEndpoint: https://beaconcha.in/api/v1/client/metrics
    bitflyMachineName: Smartnode
    bitflySecret: ""
  fallbackNode:
    enabled: false
    normal:
      consensusEndpoint:
      executionEndpoint:
    prysm:
      consensusEndpoint:
      executionEndpoint:
      jsonRpcEndpoint:
  rescueNode:
    enabled: false
    username:
    password:
  smoothingPool: false

mevBoost:
  enabled: false
  relays: []
  port: 18550

smartNode:
  image:
    repository: docker.io/rocketpool/smartnode
    tag: ""

  metrics:
    enabled: true
    port: 9102

watchtower:
  image:
    repository: docker.io/rocketpool/smartnode
    tag: ""

  metrics:
    enabled: true
    port: 9102

  maxFeeOverride: 200
  prioFeeOverride: 3

# See documentation for options:
# https://github.com/ethpandaops/ethereum-helm-charts
ethereumNode:
  # Execution Layer clients
  besu:
    defaultCommandTemplate: |
      - sh
      - -ac
      - >
        exec besu
        --data-path=/data
        --nat-method=KUBERNETES
        --rpc-http-enabled
        --rpc-http-host=0.0.0.0
        --rpc-http-port={{ .Values.httpPort }}
        --rpc-http-cors-origins=*
        --rpc-ws-enabled
        --rpc-ws-host=0.0.0.0
        --rpc-ws-port={{ .Values.wsPort }}
        --host-allowlist=*
        --engine-jwt-secret=/data/jwt.hex
        --engine-rpc-port={{ .Values.authPort }}
        --engine-host-allowlist=*
        --metrics-enabled
        --metrics-host=0.0.0.0
        --metrics-port={{ .Values.metricsPort }}
        --data-storage-format=bonsai
        --sync-mode=X_SNAP
        --Xsnapsync-synchronizer-flat-db-healing-enabled=true
        --fast-sync-min-peers=3
        --rpc-http-max-active-connections=1024
      {{- range .Values.extraArgs }}
        {{ tpl . $ }}
      {{- end }}

    authPort: 8551
    httpPort: 8545
    metricsPort: 9545
    p2pPort: 30303
    wsPort: 8546

    rbac:
      create: false
    serviceAccount:
      create: false
  erigon:
    rbac:
      create: false
    serviceAccount:
      create: false
  ethereumjs:
    rbac:
      create: false
    serviceAccount:
      create: false
  geth:
    rbac:
      create: false
    serviceAccount:
      create: false
  nethermind:
    rbac:
      create: false
    serviceAccount:
      create: false
  reth:
    rbac:
      create: false
    serviceAccount:
      create: false

  # Consensus Layer clients
  grandine:
    rbac:
      create: false
    serviceAccount:
      create: false
  lighthouse:
    image:
      tag: latest-modern

    httpPort: 5052
    metricsPort: 5054
    p2pPort: 9001

    rbac:
      create: false
    serviceAccount:
      create: false
  lodestar:
    rbac:
      create: false
    serviceAccount:
      create: false
  nimbus:
    rbac:
      create: false
    serviceAccount:
      create: false
  prysm:
    rbac:
      create: false
    serviceAccount:
      create: false
  teku:
    rbac:
      create: false
    serviceAccount:
      create: false

lighthouse:
  nameOverride: validator
  enabled: false
  mode: validator
  defaultValidatorCommandTemplate: |
    - sh
    - -ac
    - >
      exec lighthouse
      --network {{ .Values.global.main.network }}
      --datadir /data/data/validators/lighthouse
      validator
      --init-slashing-protection
      --logfile-max-number 0
      --beacon-nodes http://{{ .Release.Name }}-beacon:5052
      --suggested-fee-recipient $(cat /data/data/validators/rp-fee-recipient.txt)
      --enable-doppelganger-protection
      --metrics
      --metrics-address 0.0.0.0
      --metrics-port {{ .Values.metricsPort }}
    {{- range .Values.extraArgs }}
      {{ tpl . $ }}
    {{- end }}
  rbac:
    create: false
  serviceAccount:
    create: false

  extraVolumeMounts:
    - name: data
      mountPath: /data
  extraVolumes:
    - name: data
      persistentVolumeClaim:
        claimName: smartnode-data

  # FIXME: maybe use default
  metricsPort: 9101

prysmValidator:
  nameOverride: prysm-validator
  enabled: false
  mode: validator
  extraArgs:
    - --network
    - *global-network
  rbac:
    create: false
  serviceAccount:
    create: false
 
networkPolicy:
  create: false

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
