apiVersion: v1
kind: ConfigMap
metadata:
  name: smartnode-config
data:
  user-settings.yaml: |
    # FIXME: Use init container to inject credentials from a secret.
    addons-rescue-node:
      enabled: {{ .Values.rocketPool.rescueNode.enabled }}
      username: {{ .Values.rocketPool.rescueNode.username }}
      password: {{ .Values.rocketPool.rescueNode.password }}
    bitflyNodeMetrics:
      bitflyEndpoint: {{ .Values.rocketPool.bitflyNodeMetrics.bitflyEndpoint }}
      bitflyMachineName: {{ .Values.rocketPool.bitflyNodeMetrics.bitflyMachineName }}
      bitflySecret: {{ .Values.rocketPool.bitflyNodeMetrics.bitflySecret }}
    consensusCommon:
      apiPort: {{ include "rocketpool.consensusClient.httpPort" . }}
      # FIXME
      checkpointSyncUrl: ""
      # FIXME
      doppelgangerDetection: true
      graffiti: ""
      openApiPort: closed
      p2pPort: {{ include "rocketpool.consensusClient.p2pPort" . }}
    executionCommon:
      enginePort: {{ include "rocketpool.executionClient.enginePort" . }}
      ethstatsLabel: ""
      ethstatsLogin: ""
      httpPort: {{ include "rocketpool.executionClient.httpPort" . }}
      openRpcPorts: closed
      p2pPort: {{ include "rocketpool.executionClient.p2pPort" . }}
      wsPort: {{ include "rocketpool.executionClient.wsPort" . }}
    fallbackNormal:
      ccHttpUrl: {{ .Values.rocketPool.fallbackNode.normal.consensusEndpoint }}
      ecHttpUrl: {{ .Values.rocketPool.fallbackNode.normal.executionEndpoint }}
    fallbackPrysm:
      ccHttpUrl: {{ .Values.rocketPool.fallbackNode.prysm.consensusEndpoint }}
      ecHttpUrl: {{ .Values.rocketPool.fallbackNode.prysm.executionEndpoint }}
      jsonRpcUrl: {{ .Values.rocketPool.fallbackNode.prysm.jsonRpcEndpoint }}
    mevBoost:
      additionalFlags: ""
      aestusEnabled: false
      bloxRouteMaxProfitEnabled: false
      bloxRouteRegulatedEnabled: false
      edenEnabled: false
      enableRegulatedAllMev: false
      enableUnregulatedAllMev: false
      externalUrl: ""
      flashbotsEnabled: false
      mode: external
      openRpcPort: closed
      port: {{ .Values.mevBoost.port }}
      selectionMode: profile
      ultrasoundEnabled: false
    native:
      ccHttpUrl: http://{{ .Release.Name }}-beacon:{{ include "rocketpool.consensusClient.httpPort" . }}
      consensusClient: {{ include "rocketpool.consensusClient" . }}
      ecHttpUrl: http://{{ .Release.Name }}-execution:{{ include "rocketpool.executionClient.httpPort" . }}
      validatorRestartCommand: /scripts/restart-validator.sh
      validatorStopCommand: /scripts/stop-validator.sh
    root:
      bnMetricsPort: {{ include "rocketpool.consensusClient.metricsPort" . }}
      consensusClient: {{ include "rocketpool.consensusClient" . }}
      consensusClientMode: external
      ecMetricsPort: {{ include "rocketpool.executionClient.metricsPort" . }}
      enableBitflyNodeMetrics: false
      enableMetrics: false
      enableMevBoost: {{ .Values.mevBoost.enabled }}
      enableODaoMetrics: false
      consensusClient: {{ include "rocketpool.executionClient" . }}
      executionClientMode: external
      exporterMetricsPort: "9103"
      externalConsensusClient: {{ include "rocketpool.consensusClient" . }}
      isNative: true
      nodeMetricsPort: {{ .Values.smartNode.metricsPort }}
      reconnectDelay: 60s
      rpDir: /data
      useFallbackClients: {{ .Values.rocketPool.fallbackNode.enabled }}
      vcMetricsPort: {{ include "rocketpool.validatorClient.metricsPort" . }}
      version: v{{ .Chart.AppVersion }}
      watchtowerMetricsPort: {{ .Values.watchtower.metricsPort }}
    smartnode:
      archiveECUrl: ""
      checkpointRetentionLimit: "200"
      dataPath: /data/data
      distributeThreshold: "1"
      manualMaxFee: "0"
      minipoolStakeGasThreshold: "150"
      network: {{ .Values.global.main.network }}
      priorityFee: "2"
      projectName: rocketpool
      recordCheckpointInterval: "45"
      recordsPath: /data/data/records
      rewardsTreeCustomUrl: ""
      rewardsTreeMode: download
      useRollingRecords: false
      watchtowerMaxFeeOverride: {{ .Values.watchtower.maxFeeOverride }}
      watchtowerPrioFeeOverride: {{ .Values.watchtower.prioFeeOverride }}
