apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketpool.fullname" . }}-smartnode-config
data:
  user-settings.yaml: |
    # FIXME: Use init container to inject credentials from a secret.
    addons-rescue-node:
      {{- if (get .Values.rocketPool "addons-rescue-node") }}
      {{- (get .Values.rocketPool "addons-rescue-node") | toYaml | nindent 6 -}}
      {{- end }}
    bitflyNodeMetrics:
      {{- if .Values.rocketPool.bitflyNodeMetrics }}
      {{- .Values.rocketPool.bitflyNodeMetrics | toYaml | nindent 6 -}}
      {{- end }}
    {{- if .Values.fallbackNode.enabled }}
    {{- if .Values.fallbackNode.prysm.enabled }}
    fallbackNormal:
      ccHttpUrl:
      ecHttpUrl:
    fallbackPrysm:
      ccHttpUrl: http://{{ .Release.Name }}-rocketpool-fallback-beacon:{{ (include "rocketpool.consensusClient" .Values.fallbackNode | fromJson).httpPort }}
      ecHttpUrl: http://{{ .Release.Name }}-rocketpool-fallback-execution:{{ (include "rocketpool.executionClient" .Values.fallbackNode | fromJson).httpPort }}
      jsonRpcUrl: {{ .Values.rocketPool.fallbackNode.prysm.jsonRpcEndpoint }}
    {{- else }}
    fallbackNormal:
      ccHttpUrl: http://{{ .Release.Name }}-rocketpool-fallback-beacon:{{ (include "rocketpool.consensusClient" .Values.fallbackNode | fromJson).httpPort }}
      ecHttpUrl: http://{{ .Release.Name }}-rocketpool-fallback-execution:{{ (include "rocketpool.executionClient" .Values.fallbackNode |  fromJson).httpPort }}
    fallbackPrysm:
      ccHttpUrl:
      ecHttpUrl:
      jsonRpcUrl:
    {{- end }}
    {{- else }}
    fallbackNormal:
      ccHttpUrl:
      ecHttpUrl:
    fallbackPrysm:
      ccHttpUrl:
      ecHttpUrl:
      jsonRpcUrl:
    {{- end }}
    mevBoost:
      externalUrl: ''
      mode: external
      openRpcPort: closed
      port: {{ .Values.mevBoost.port }}
      {{- if .Values.rocketPool.mevBoost }}
      {{- .Values.rocketPool.mevBoost | toYaml | nindent 6 -}}
      {{- end }}
    native:
      ccHttpUrl: http://{{ .Release.Name }}-rocketpool-primary-beacon:{{ (include "rocketpool.consensusClient" .Values.primaryNode | fromJson).httpPort }}
      consensusClient: {{ (include "rocketpool.consensusClient" .Values.primaryNode | fromJson).name }}
      ecHttpUrl: http://{{ .Release.Name }}-rocketpool-primary-execution:{{ (include "rocketpool.executionClient" .Values.primaryNode | fromJson).httpPort }}
      validatorRestartCommand: /scripts/restart-validator.sh
      validatorStopCommand: /scripts/stop-validator.sh
      {{- if .Values.rocketPool.native }}
      {{- .Values.rocketPool.native | toYaml | nindent 6 -}}
      {{- end }}
    root:
      bnMetricsPort: {{ (include "rocketpool.consensusClient" .Values.primaryNode | fromJson).metricsPort }}
      consensusClient: {{ (include "rocketpool.consensusClient" .Values.primaryNode | fromJson).name }}
      consensusClientMode: external
      ecMetricsPort: {{ (include "rocketpool.executionClient" .Values.primaryNode | fromJson).metricsPort }}
      enableMetrics: true
      enableMevBoost: {{ .Values.mevBoost.enabled }}
      executionClientMode: external
      exporterMetricsPort: 9103
      externalConsensusClient: {{ (include "rocketpool.consensusClient" .Values.primaryNode | fromJson).name }}
      isNative: true
      nodeMetricsPort: {{ .Values.smartNode.metricsPort }}
      rpDir: /data
      useFallbackClients: {{ .Values.fallbackNode.enabled }}
      vcMetricsPort: {{ include "rocketpool.validatorClient.metricsPort" . }}
      version: v{{ .Chart.AppVersion }}
      watchtowerMetricsPort: {{ .Values.watchtower.metricsPort }}
      {{- if .Values.rocketPool.root }}
      {{- .Values.rocketPool.root | toYaml | nindent 6 -}}
      {{- end }}
    smartnode:
      dataPath: /data/data
      network: {{ .Values.global.main.network | required ".Values.global.main.network is required." }}
      projectName: rocketpool
      recordsPath: /data/data/records
      {{- if .Values.rocketPool.smartnode }}
      {{- .Values.rocketPool.smartnode | toYaml | nindent 6 -}}
      {{- end }}
    {{- if .Values.rocketPool.extraConfig }}
    {{- .Values.rocketPool.extraConfig | toYaml | nindent 4 -}}
    {{- end }}
