apiVersion: v1
kind: ConfigMap
metadata:
  name: smartnode-config
data:
  user-settings.yaml: |
    # FIXME: Use init container to inject credentials from a secret.
    addons-rescue-node:
      enabled: {{ .Values.rocketPool.rescueNode.enabled }}
      username: {{ .Values.rocketPool.rescueNode.username }}
      password: {{ .Values.rocketPool.rescueNode.password }}
    bitflyNodeMetrics:
      bitflyEndpoint: {{ .Values.rocketPool.bitflyNodeMetrics.bitflyEndpoint }}
      bitflyMachineName: {{ .Values.rocketPool.bitflyNodeMetrics.bitflyMachineName }}
      bitflySecret: {{ .Values.rocketPool.bitflyNodeMetrics.bitflySecret }}
    {{- if .Values.fallbackNode.enabled }}
    {{- if .Values.fallbackNode.prysm.enabled }}
    fallbackNormal:
      ccHttpUrl:
      ecHttpUrl:
    fallbackPrysm:
      ccHttpUrl: http://{{ .Release.Name }}-rocketpool-fallback-beacon:{{ include "rocketpool.fallbackConsensusClient.httpPort" . }}
      ecHttpUrl: http://{{ .Release.Name }}-rocketpool-fallback-execution:{{ include "rocketpool.fallbackExecutionClient.httpPort" . }}
      jsonRpcUrl: {{ .Values.rocketPool.fallbackNode.prysm.jsonRpcEndpoint }}
    {{- else }}
    fallbackNormal:
      ccHttpUrl: http://{{ .Release.Name }}-rocketpool-fallback-beacon:{{ include "rocketpool.fallbackConsensusClient.httpPort" . }}
      ecHttpUrl: http://{{ .Release.Name }}-rocketpool-fallback-execution:{{ include "rocketpool.fallbackExecutionClient.httpPort" . }}
    fallbackPrysm:
      ccHttpUrl:
      ecHttpUrl:
      jsonRpcUrl:
    {{- end }}
    {{- else }}
    fallbackNormal:
      ccHttpUrl:
      ecHttpUrl:
    fallbackPrysm:
      ccHttpUrl:
      ecHttpUrl:
      jsonRpcUrl:
    {{- end }}
    mevBoost:
      additionalFlags: ''
      aestusEnabled: false
      bloxRouteMaxProfitEnabled: false
      bloxRouteRegulatedEnabled: false
      edenEnabled: false
      enableRegulatedAllMev: false
      enableUnregulatedAllMev: false
      externalUrl: ''
      flashbotsEnabled: false
      mode: external
      openRpcPort: closed
      port: {{ .Values.mevBoost.port }}
      selectionMode: profile
      ultrasoundEnabled: false
    native:
      ccHttpUrl: http://{{ .Release.Name }}-rocketpool-primary-beacon:{{ include "rocketpool.primaryConsensusClient.httpPort" . }}
      consensusClient: {{ include "rocketpool.primaryConsensusClient.name" . }}
      ecHttpUrl: http://{{ .Release.Name }}-rocketpool-primary-execution:{{ include "rocketpool.primaryExecutionClient.httpPort" . }}
      validatorRestartCommand: /scripts/restart-validator.sh
      validatorStopCommand: /scripts/stop-validator.sh
    root:
      bnMetricsPort: {{ include "rocketpool.primaryConsensusClient.metricsPort" . }}
      consensusClient: {{ include "rocketpool.primaryConsensusClient.name" . }}
      consensusClientMode: external
      ecMetricsPort: {{ include "rocketpool.primaryExecutionClient.metricsPort" . }}
      enableBitflyNodeMetrics: false
      enableMetrics: true
      enableMevBoost: {{ .Values.mevBoost.enabled }}
      enableODaoMetrics: false
      executionClientMode: external
      exporterMetricsPort: 9103
      externalConsensusClient: {{ include "rocketpool.primaryConsensusClient.name" . }}
      isNative: true
      nodeMetricsPort: {{ .Values.smartNode.metricsPort }}
      reconnectDelay: 60s
      rpDir: /data
      useFallbackClients: {{ .Values.fallbackNode.enabled }}
      vcMetricsPort: {{ include "rocketpool.validatorClient.metricsPort" . }}
      version: v{{ .Chart.AppVersion }}
      watchtowerMetricsPort: {{ .Values.watchtower.metricsPort }}
    smartnode:
      archiveECUrl: ''
      checkpointRetentionLimit: 200
      dataPath: /data/data
      distributeThreshold: 1
      manualMaxFee: 0
      minipoolStakeGasThreshold: 150
      network: {{ .Values.global.main.network }}
      priorityFee: 2
      projectName: rocketpool
      recordCheckpointInterval: 45
      recordsPath: /data/data/records
      rewardsTreeCustomUrl: ''
      rewardsTreeMode: download
      useRollingRecords: false
      watchtowerMaxFeeOverride: {{ .Values.watchtower.maxFeeOverride }}
      watchtowerPrioFeeOverride: {{ .Values.watchtower.prioFeeOverride }}
