{{- if .Values.mevBoost.enabled -}}
{{- if eq .Values.global.main.network "holesky" }}
{{- fail "The holesky network does not support mev-boost" }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rocketpool.fullname" . }}-mev-boost
  labels:
    app.kubernetes.io/component: mev-boost
    {{- include "rocketpool.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: mev-boost
      {{- include "rocketpool.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mev-boost
        {{- include "rocketpool.labels" . | nindent 8 }}
    spec:
      containers:
        - name: mev-boost
          image: {{ .Values.mevBoost.image.repository }}:{{ .Values.mevBoost.image.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - /app/mev-boost
          args:
            - -{{ .Values.global.main.network }}
            - -addr=[::]:{{ .Values.mevBoost.port }}
            - -relay-check
            - -relays={{ join "," .Values.mevBoost.relays }}
          ports:
            - name: api
              containerPort: {{ .Values.mevBoost.port }}
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketpool.fullname" . }}-mev-boost
  labels:
    app.kubernetes.io/component: mev-boost
    {{- include "rocketpool.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.mevBoost.port }}
      targetPort: {{ .Values.mevBoost.port }}
  selector:
    app.kubernetes.io/component: mev-boost
    {{- include "rocketpool.labels" . | nindent 4 }}
{{- end }}
