{{- if .Values.smartNode.podMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "rocketpool.fullname" . }}-smartnode
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: smartnode
      {{ include "rocketpool.selectorLabels" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "rocketpool.fullname" . }}-watchtower
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: watchtower
      {{ include "rocketpool.selectorLabels" . }}
{{- end }}
