apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketpool.fullname" . }}-smartnode-scripts
data:
  post-start.sh: |
    #!/bin/sh

    VERSION="v{{ .Values.smartNode.image.tag | default .Chart.AppVersion }}"

    if ! command -v curl >/dev/null; then
      apt update && apt install -y curl
    fi

    curl \
      --output /tmp/rocketpool \
      -L "https://github.com/rocket-pool/smartnode-install/releases/download/$VERSION/rocketpool-cli-linux-amd64"
    chmod +x /tmp/rocketpool
  rocketpool: |
    #!/bin/sh

    # FIXME: don't run as root
    # FIXME: query API through RPC instead of this hack (coming in smartnode v2)
    /tmp/rocketpool --allow-root --config-path=/data --daemon-path=/go/bin/rocketpool $@
  restart-validator.sh: |
    #!/bin/sh

    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

    # FIXME: race between getting called and post start script running
    if ! command -v curl >/dev/null; then
      sleep 15
    fi

    curl \
      --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
      --header "Authorization: Bearer $TOKEN" \
      --header "Accept: application/json, */*" \
      --header "Content-Type: application/strategic-merge-patch+json" \
      --request PATCH \
      --data '{"spec":{"replicas":1,"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"'"$(date +%Y-%m-%dT%T%z)"'"}}}}}' \
      "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT_HTTPS/apis/apps/v1/namespaces/$NAMESPACE/statefulsets/{{ .Release.Name }}-rocketpool-validator"
  setup.sh: |
    #!/bin/sh
 
    mkdir -p /data/validators
    mkdir -p /data/rewards-trees
    mkdir -p /data/custom-keys
    chown -R 10001:10001 /data
    touch /data/pre-setup-complete

    read -p \
    "Launching the rocketpool service config interface.
    Please confirm that the configuration is correct.
    Note that you will not be able to change any settings here.
    Press enter to continue." unused

    /scripts/rocketpool service config

    touch /data/setup-complete

    read -p "Node wallet needs to be initialized. Proceed? [y/N] " \
      confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 0

    /scripts/rocketpool wallet init
  stop-validator.sh: |
    #!/bin/sh

    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

    # FIXME: race between getting called and post start script running
    if ! command -v curl >/dev/null; then
      sleep 15
    fi

    curl \
      --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
      --header "Authorization: Bearer $TOKEN" \
      --header "Accept: application/json, */*" \
      --header "Content-Type: application/strategic-merge-patch+json" \
      --request PATCH \
      --data '{"spec":{"replicas":0}}' \
      "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT_HTTPS/apis/apps/v1/namespaces/$NAMESPACE/statefulsets/{{ .Release.Name }}-rocketpool-validator"
