apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rocketpool.fullname" . }}-setup
  labels:
    app.kubernetes.io/component: setup
    {{- include "rocketpool.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: setup
        {{- include "rocketpool.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init
          image: busybox
          command:
            - chown
            - -R
            - 10001:10001
            - /data
          volumeMounts:
            - name: data
              mountPath: /data
      restartPolicy: Never
      containers:
        - name: setup
          image: '{{ .Values.smartNode.image.repository }}:v{{ .Values.smartNode.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - while [ ! -f /data/setup-complete ]; do sleep 5; done
          env:
            - name: PATH
              value: /scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - /scripts/post-start.sh
          volumeMounts:
            - name: config
              mountPath: /data/user-settings.yml
              subPath: user-settings.yaml
            - name: data
              mountPath: /data
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: smartnode-config
        - name: data
          persistentVolumeClaim:
            claimName: rocketpool-smartnode-data
        - name: scripts
          configMap:
            defaultMode: 0755
            name: smartnode-scripts
