apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rocketpool.fullname" . }}-watchtower
  labels:
    app.kubernetes.io/component: watchtower
    app.kubernetes.io/name: watchtower
    app.kubernetes.io/part-of: rocketpool
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: watchtower
      app.kubernetes.io/name: watchtower
      app.kubernetes.io/part-of: rocketpool
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: '{{ .Values.watchtower.metrics.enabled }}'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '{{ .Values.watchtower.metrics.port }}'
      labels:
        app.kubernetes.io/component: watchtower
        app.kubernetes.io/name: watchtower
        app.kubernetes.io/part-of: rocketpool
    spec:
      containers:
        - name: smartnode
          image: "{{ .Values.smartNode.image.repository }}:v{{ .Values.smartNode.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args:
            - --metricsAddress
            - 0.0.0.0
            - --metricsPort
            - '{{ .Values.watchtower.metrics.port }}'
            - --settings
            - /config/user-settings.yaml
            - watchtower
          ports:
            - name: metrics
              containerPort: {{ .Values.watchtower.metrics.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: smartnode-config
        - name: data
          persistentVolumeClaim:
            claimName: smartnode-data
